# Generated by Django 3.1.5 on 2021-09-19 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='用戶名稱')),
                ('password', models.CharField(max_length=255, verbose_name='密碼')),
                ('phone', models.CharField(max_length=255, verbose_name='電話')),
                ('address', models.CharField(max_length=255, verbose_name='地址')),
                ('created_time', models.DateTimeField(auto_now=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
