# Generated by Django 3.1.5 on 2021-10-05 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paypal_id',
            field=models.CharField(default='<paypal_id>', max_length=255, verbose_name='paypal訂單編號'),
            preserve_default=False,
        ),
    ]
