# Generated by Django 3.1.5 on 2021-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.IntegerField(default=0, verbose_name='種類'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.TextField(default='', verbose_name='詳細描述'),
            preserve_default=False,
        ),
    ]
